# Minimal Text Template
"$schema" = "https://starship.rs/config-schema.json"

palette = "custom"
add_newline = false

# dir git model context cost
format = """
$directory \
$git_branch$git_status \
${env_var.CLAUDE_MODEL} \
${env_var.CLAUDE_CONTEXT} \
${env_var.CLAUDE_COST}\
"""

[directory]
style = "fg:directory"
format = "[$path]($style)"
truncation_length = 2
truncate_to_repo = true

[git_branch]
symbol = ""
style = "fg:git_branch"
format = "[$branch]($style)"

[git_status]
style = "fg:git_status"
format = "[($all_status$ahead_behind)]($style)"

[env_var.CLAUDE_MODEL]
variable = "CLAUDE_MODEL"
format = "[$env_value]($style)"
style = "fg:model"

[env_var.CLAUDE_CONTEXT]
variable = "CLAUDE_CONTEXT"
format = "[$env_value]($style)"
style = "fg:context"

[env_var.CLAUDE_COST]
variable = "CLAUDE_COST"
format = "[$env_value]($style)"
style = "fg:cost"

## Custom palette
#

# Dracula
[palettes.custom]
claude = "#D97757"
claude_bg = "#44475a"

directory = "#8be9fd"
directory_bg = "#282a36"

git_branch = "#bd93f9"
git_status = "#ff6e6e"
git_bg = "#44475a"

model = "#8be9fd"
model_bg = "#282a36"

context = "#ffb86c"
context_bg = "#44475a"

cost = "#50fa7b"
cost_bg = "#4d4f68"
