#!/bin/bash
set -euo pipefail

# This wrapper script monkey-patches the environment to ensure that Homebrew can runs smoothly
# even if shell is not properly configured to use Homebrew.

# If brew command is available, use it
if command -v brew &>/dev/null; then
    brew "${@}"
    exit 0
fi

# Setup homebrew for this particular shell
UNAME_MACHINE="$(/usr/bin/uname -m)"
if [[ "${UNAME_MACHINE}" == "arm64" ]]; then
    # On ARM macOS, this script installs to /opt/homebrew only
    HOMEBREW_PREFIX="/opt/homebrew"
else
    # On Intel macOS, this script installs to /usr/local only
    HOMEBREW_PREFIX="/usr/local"
fi
eval "$(${HOMEBREW_PREFIX}/bin/brew shellenv)"

"${HOMEBREW_PREFIX}/bin/brew" "${@}"
