#!/bin/zsh

# Reset source directories permissions
compaudit | xargs chmod g-w,o-w
compaudit | xargs chown "$(whoami)"

# Remove cached files
rm -f "${HOME}/.zcompdump*"

# Delete all compiled zinit plugins
zinit delete --all
