repos:
  - repo: local
    hooks:
      - id: eslint-json
        name: JSON should be formatted and sorted
        entry: eslint
        language: node
        additional_dependencies:
          - eslint
          - "@eslint/json"
        files: \.json$
        types: [file]
      - id: chmod-sh
        name: Shell script should be executable
        entry: bin/chmod-sh
        language: system
        files: \.sh$
