repos:
  - repo: local
    hooks:
      - id: eslint-json
        name: ESLint (JSON)
        entry: eslint
        language: node
        additional_dependencies:
          - eslint
          - "@eslint/json"
        files: \.json$
        types: [file]
