#!/bin/zsh

tmppath="$(which "${1}")"
if [[ "$tmppath" == *".pyenv"* ]]; then
    pyenv which "${1}"
elif [[ "$tmppath" == *".rbenv"* ]]; then
    rbenv which "${1}"
elif [[ "$tmppath" == *".nodenv"* ]]; then
    nodenv which "${1}"
else
    realpath "$(which "${1}")"
fi
