# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[aws]
disabled = true

[docker_context]
disabled = true

[gcloud]
disabled = true

[time]
disabled = false
format = '🕙 [\[ $time \]]($style) '
time_format = '%T'
utc_time_offset = '-5'
# time_range = '10:00:00-14:00:00'
