#! /bin/bash
# alias: brew refresh
#:  * `refresh` [args...]
#:    `brew refresh` is an alias for `brew update && brew outdated && brew upgrade && brew cleanup`
brew update && brew outdated && brew upgrade && brew cleanup $*
