alias gitconfig="${EDITOR} ~/.gitconfig"
alias hostsconfig="${EDITOR} /etc/hosts"
alias p10kconfig="${EDITOR} ~/.p10k.zsh"
alias sshconfig="${EDITOR} ~/.ssh/config"
alias zshconfig="${EDITOR} ~/.zshrc"
