alias "npi"="npm install"
alias "npig"="npm install --global"
alias "npid"="npm install --save-dev"
alias "npin"="npm init"
alias "npll"="npm list"
alias "npl"="npm list --depth=0"
alias "npo"="npm outdated"
alias "npr"="npm run"
alias "npst"="npm start"
alias "nptt"="npm test"
