#!/bin/zsh

# Reset source directories permissions
compaudit | xargs chmod g-w,o-w
compaudit | xargs chown "${USER}"

# Remove cached files
rm -f "${HOME}/.zcompdump*"
rm -rf "${HOME}/.local/share/zinit"
