name: Deploy install script to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - "install/install.sh"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ github.token }}
          publish_dir: ./install
          cname: init.tomy.tech
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
